name: Deploy To Docker Hub

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    environment: PRODUCAO 

    env:
      IMAGE_BASENAME: kroki-client
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}       
      IMAGE_TAG: ${{ github.sha }}
     
    steps:
      - name: Set FULL_IMAGE_NAME
        run: echo "FULL_IMAGE_NAME=$DOCKERHUB_USERNAME/$IMAGE_BASENAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
            docker build -t $FULL_IMAGE_NAME .

      - name: Set FULL_LATEST_IMAGE_NAME
        run: echo "FULL_LATEST_IMAGE_NAME=$DOCKERHUB_USERNAME/$IMAGE_BASENAME:latest" >> $GITHUB_ENV

      - name: Tag the latest image
        run: |
            docker tag $FULL_LATEST_IMAGE_NAME $FULL_IMAGE_NAME

      - name: Push to Docker Hub
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DOCKERHUB_TOKEN
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
          docker push $FULL_IMAGE_NAME      
