name: Build Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: PRODUCAO 

    env:
      IMAGE_BASENAME: kroki-client
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}       
      IMAGE_TAG: ${{ github.sha }}
     
    steps:
      # Definir a variável FULLFILENAME no primeiro step
      - name: Set FULLFILENAME
        run: echo "FULLFILENAME=$DOCKERHUB_USERNAME/$IMAGE_BASENAME:$IMAGE_TAG" >> $GITHUB_ENV

      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image
      - name: Build Docker image
        run: |
            docker build -t $FULLFILENAME .

      # # Push the Docker image
      # - name: Push Docker image
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      #   run: |
      #     echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      #     docker push $FULL_IMAGE_NAME      
