name: TestBuildingProcess

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_BASENAME: kroki-client
      IMAGE_TAG: ${{ github.ref == 'refs/heads/main' && 'autotest' || github.sha }}
      FULL_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/$IMAGE_BASENAME:$IMAGE_TAG

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    #   # Log in to Docker Hub (you can configure your Docker Hub credentials in GitHub Secrets)
    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v2
    #     with:
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t $FULL_IMAGE_NAME .

    #   # Run tests inside the built container
    #   - name: Run container tests
    #     run: |
    #       docker run --rm $FULL_IMAGE_NAME sh -c "curl --version"
      
