name: TestBuildingProcess

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: PRODUCAO 

    env:
      IMAGE_BASENAME: kroki-client
      IMAGE_TAG: ${{ github.sha }}
      FULL_IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/$IMAGE_BASENAME:$IMAGE_TAG
      segredao: ${{ vars.DOCKERHUB_USERNAME }}          

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the Docker image
      - name: Build Docker image
        env:
          segredim: ${{ vars.DOCKERHUB_USERNAME }}          
        run: |
            docker build -t $segredao .

      # # Push the Docker image
      # - name: Push Docker image
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      #   run: |
      #     echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      #     docker push $FULL_IMAGE_NAME      
